import * as https from 'https';
import * as http from 'http';
import { parseLlmFindings, LlmFinding } from './checks';

export type LlmProvider = 'claude' | 'openai' | 'gemini' | 'none';

export interface LlmConfig {
  provider: LlmProvider;
  apiKey: string;
  endpointOverride: string;
  model: string;
}

export const LLM_TIMEOUT_MS = 30_000;

const DEFAULT_MODELS: Record<Exclude<LlmProvider, 'none'>, string> = {
  claude: 'claude-sonnet-4-6',
  openai: 'gpt-4o-mini',
  gemini: 'gemini-2.0-flash',
};

const DEFAULT_ENDPOINTS: Record<Exclude<LlmProvider, 'none'>, string> = {
  claude: 'https://api.anthropic.com/v1/messages',
  openai: 'https://api.openai.com/v1/chat/completions',
  gemini: 'https://generativelanguage.googleapis.com/v1beta',
};

export const SYSTEM_PROMPT = `You are a code quality auditor for the "AI Quality Gate" VS Code extension. You analyze source code — especially code that may have been generated by an AI coding assistant — and identify quality issues that a human reviewer should address before merging.

Analyze the code below and return findings as a JSON array. Each element must be an object with these fields:
- "severity": 1 (Error — likely bug or security issue), 2 (Warning — code smell or potential problem), 3 (Info — suggestion for improvement)
- "line": the 1-based line number where the issue starts
- "endLine": the 1-based line number where the issue ends (same as "line" for single-line issues)
- "message": a concise, actionable description of the issue

Focus on issues that AI code generators commonly introduce:
- Hallucinated APIs: calls to functions, methods, classes, or modules that do not exist in the language/framework, or that use incorrect signatures
- Logic errors: off-by-one errors, inverted conditions, missing edge cases, incorrect operator precedence
- Security vulnerabilities: injection flaws, missing input validation, insecure defaults, path traversal
- Over-engineering: unnecessarily complex abstractions, premature generalization, or patterns that add indirection without value
- Dead or unreachable code that serves no purpose
- Resource leaks: unclosed handles, missing cleanup, event listeners never removed

Do NOT flag:
- Style preferences (formatting, naming conventions)
- Missing comments or documentation
- Performance micro-optimizations unless they cause measurable issues

Return ONLY a valid JSON array with no surrounding text, markdown, or code fences. If no issues are found, return an empty array: []`;

interface ProviderRequest {
  url: string;
  headers: Record<string, string>;
  body: string;
}

function buildRequest(config: LlmConfig, code: string, fileName: string): ProviderRequest {
  const provider = config.provider as Exclude<LlmProvider, 'none'>;
  const model = config.model || DEFAULT_MODELS[provider];
  const baseEndpoint = config.endpointOverride || DEFAULT_ENDPOINTS[provider];
  const userMessage = `File: ${fileName}\n\n\`\`\`\n${code}\n\`\`\``;

  switch (provider) {
    case 'claude':
      return {
        url: baseEndpoint,
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': config.apiKey,
          'anthropic-version': '2023-06-01',
        },
        body: JSON.stringify({
          model,
          max_tokens: 4096,
          system: SYSTEM_PROMPT,
          messages: [{ role: 'user', content: userMessage }],
        }),
      };

    case 'openai':
      return {
        url: baseEndpoint,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${config.apiKey}`,
        },
        body: JSON.stringify({
          model,
          messages: [
            { role: 'system', content: SYSTEM_PROMPT },
            { role: 'user', content: userMessage },
          ],
        }),
      };

    case 'gemini': {
      const url = `${baseEndpoint}/models/${model}:generateContent?key=${config.apiKey}`;
      return {
        url,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          system_instruction: { parts: [{ text: SYSTEM_PROMPT }] },
          contents: [{ parts: [{ text: userMessage }] }],
          generationConfig: { responseMimeType: 'application/json' },
        }),
      };
    }
  }
}

function extractResponseText(provider: Exclude<LlmProvider, 'none'>, body: unknown): string {
  const obj = body as Record<string, any>;
  switch (provider) {
    case 'claude':
      return obj?.content?.[0]?.text ?? '';
    case 'openai':
      return obj?.choices?.[0]?.message?.content ?? '';
    case 'gemini':
      return obj?.candidates?.[0]?.content?.parts?.[0]?.text ?? '';
  }
}

function httpRequest(url: string, headers: Record<string, string>, body: string): Promise<{ status: number; body: string }> {
  return new Promise((resolve, reject) => {
    const parsed = new URL(url);
    const options: http.RequestOptions = {
      hostname: parsed.hostname,
      port: parsed.port || (parsed.protocol === 'https:' ? 443 : 80),
      path: parsed.pathname + parsed.search,
      method: 'POST',
      headers: {
        ...headers,
        'Content-Length': Buffer.byteLength(body).toString(),
      },
    };

    const reqModule = parsed.protocol === 'https:' ? https : http;
    const req = reqModule.request(options, (res) => {
      let data = '';
      res.on('data', (chunk: string) => { data += chunk; });
      res.on('end', () => resolve({ status: res.statusCode ?? 0, body: data }));
    });

    req.on('error', reject);
    req.setTimeout(LLM_TIMEOUT_MS, () => {
      req.destroy(new Error('LLM request timed out'));
    });

    req.write(body);
    req.end();
  });
}

export interface LlmLogger {
  info(msg: string): void;
  error(msg: string): void;
}

export async function callLlm(
  code: string,
  uri: string,
  config: LlmConfig,
  lineCount: number,
  logger?: LlmLogger
): Promise<LlmFinding[]> {
  if (config.provider === 'none' || !config.apiKey) {
    return [];
  }

  const provider = config.provider as Exclude<LlmProvider, 'none'>;
  const fileName = uri.split('/').pop() ?? 'unknown';
  const request = buildRequest(config, code, fileName);

  try {
    logger?.info(`Sending code to ${provider} for analysis...`);
    const response = await httpRequest(request.url, request.headers, request.body);

    if (response.status !== 200) {
      logger?.error(`${provider} API returned status ${response.status}: ${response.body.slice(0, 200)}`);
      return [];
    }

    const parsed = JSON.parse(response.body);
    const text = extractResponseText(provider, parsed);
    const findings = parseLlmFindings(text, lineCount);
    logger?.info(`${provider} returned ${findings.length} finding(s)`);
    return findings;
  } catch (err: any) {
    logger?.error(`${provider} error: ${err?.message ?? err}`);
    return [];
  }
}
